### ISSUE TITLE
Error: body-file ./terraform/comment.md does not exist

### ISSUE THREAD

**Issue by DonggeunYu** [Pluralith/actions#14]
I used the following yaml. But I get an error not finding the comment.md file.
~~~
  pluralith:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      working-directory: ./terraform
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false # This is recommended so the `terraform show` command outputs valid JSON
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}

      # Init Terraform project
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.working-directory }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        # See https://github.com/infracost/actions/tree/master/setup for other inputs
        # If you can't use this action, see Docker images in https://infracost.io/cicd
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      # Set up and authenticate Pluralith
      - name: Pluralith Init
        uses: Pluralith/actions/init@v1.3.0
        with:
          terraform-path: ${{ env.working-directory }}
          api-key: ${{ secrets.PLURALITH_API_KEY }}
          project-id: ${{ secrets.PLURALITH_PROJECT_ID }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}

      # Run Pluralith to generate an infrastructure diagram and comment body
      - name: Pluralith Run
        uses: Pluralith/actions/run@v1.3.0
        with:
          title: \#${{ github.event.number }}
          terraform-command: "plan"
          terraform-path: ${{ env.working-directory }}
          show-changes: true
          show-drift: true
          show-costs: true # Requires Infracost to be set up in your pipeline
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}

      # Post the generated diagram as a GitHub comment
      - name: Pluralith Comment
        uses: Pluralith/actions/comment@v1.3.0
        with:
          terraform-path: ${{ env.working-directory }}
          behavior: hide-and-new
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}
~~~

Error:
~~~
Error: Error: body-file ./terraform/comment.md does not exist
~~~

**Comment by DilanAriza** [comment]
I have the same problem with a similar configuration... we hope you help us with this problem.
@DanThePutzer

**Comment by DanThePutzer** [comment]
@DilanAriza thanks for reporting!

We've seen this issue before, usually it happens because the step before the comment step fails, but is marked as successful anyway.

Could you check in your action what the output for the step before the failing one says? It could say something like "No org ID given" or something like that. Let me know if that is the case and I can help fix it!

**Comment by aaron-imbrock** [comment]
I'm getting the same issue and it is related to the previous step failing, but getting marked as successful. I think.

Warning: Unexpected input(s) 'org-id', valid inputs are ['terraform-command', 'terraform-path', 'terraform-var-file', 'title', 'version', 'export-pdf', 'show-changes', 'show-drift', 'show-costs', 'cost-mode', 'cost-period', 'cost-usage-file']
Run Pluralith/actions/run@v1.4.0
Run pluralith run plan --var-file= --title= --version= --export-pdf=false --show-changes=false --show-drift=false --show-costs=false --cost-mode=delta --cost-period=month --cost-usage-file=
parsing response failed -> GetGitHubRelease: %!w(<nil>)
⠿ Initiating Plan Run ⇢ Posting To Pluralith Dashboard
 → Branch detected: main

→ Authentication
  ✔ API key is valid, you are authenticated!

→ Project Setup
  ✘ No Org ID given
PreRun: failed to verify org id -> RunInit: no org id given
0s
Run Pluralith/actions/comment@v1.4.0
  with:
    terraform-path: /home/runner/work/infrastructure/infrastructure
    behavior: update
    github-token: ***
  env:
    working-directory: /home/runner/work/infrastructure/infrastructure
    AWS_DEFAULT_REGION: us-west-2
    AWS_REGION: us-west-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    PLURALITH_GITHUB_ACTION: true
Run mv "/home/runner/work/infrastructure/infrastructure"/comment.md ./comment.md
  mv "/home/runner/work/infrastructure/infrastructure"/comment.md ./comment.md
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    working-directory: /home/runner/work/infrastructure/infrastructure
    AWS_DEFAULT_REGION: us-west-2
    AWS_REGION: us-west-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    PLURALITH_GITHUB_ACTION: true
mv: '/home/runner/work/infrastructure/infrastructure/comment.md' and './comment.md' are the same file
Error: Process completed with exit code 1.

**Comment by aaron-imbrock** [comment]
```
name: Terraform Infrastructure Documentation
on:
  push:
    branches:
      - 'main'
      
jobs:
  pluralith:
    runs-on: ubuntu-latest
    name: Run Pluralith
    env:
      working-directory: ${{ github.workspace }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      # Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-2
      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: "1.11.4"
      # Init Terraform project
      - name: Terraform Init
        run: terraform init
      # Set up and authenticate Pluralith
      - name: Pluralith Init
        uses: Pluralith/actions/init@v1.4.0
        with:
          api-key: ${{ secrets.PLURALITH_API_KEY }}
          org-id: ${{ secrets.PLURALITH_ORG_ID }}
          project-id: ${{ secrets.PLURALITH_PROJECT_ID }}
          project-name: ${{ secrets.PLURALITH_PROJECT_NAME }}
      # Run Pluralith to generate an infrastructure diagram and comment body
      - name: Pluralith Run
        uses: Pluralith/actions/run@v1.4.0
        with:
          org-id: ${{ secrets.PLURALITH_ORG_ID }}
          terraform-command: "plan"
          show-changes: false
          show-drift: false
          show-costs: false
      # Post the generated diagram as a GitHub comment
      - name: Pluralith Comment
        uses: Pluralith/actions/comment@v1.4.0
        with:
          terraform-path: ${{ github.workspace }}


```
